### ISSUE TITLE
Metadata following netCDF CF-conventions

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#1]
**Is your feature request related to a problem? Please describe.**
Stored data should be self-describing. The ability to store coordinates with a projection complying with netCDF conventions CF.

Following the standard allows for easy interaction with other programs

**Describe the solution you'd like**
Change the DataStore class to account for CF conventions.
See: <http://cfconventions.org/cf-conventions/cf-conventions.html>

Each measurement point should have a local coordinate (length along the cable) and a world coordinate (e.g., WGS84 coordinates)

Vertical temperature profiles can use 'timeSeriesProfile', chp 5.2

**Describe alternatives you've considered**
Adding metadata might be out of the scope of this project

**Additional context**
The load and save functions should continue to work.

Precision of the storage of world coordinates in the to_netcdf function should be increased.

**Comment by bdestombe** [comment]
@BSchilperoort

**Comment by bdestombe** [comment]
Oops, accidentally closed the issue

**Comment by BSchilperoort** [comment]
> Each measurement point should have a local coordinate (length along the cable) and a world coordinate (e.g., WGS84 coordinates)

while I agree that some netCDF convention should be followed, giving each point along the cable a world coordinate might not be the most practical option.

Adding some basic essentials might be the most practical, ie:
- title
- description
- site location (WGS84 lon/lat)
- data source (Institute, PI)
- history (file creation)

I do think more metadata than this will be out of scope of this project, and can be added by users to satisfy their individual needs.

**Comment by bdestombe** [comment]
Indeed Bart, this is beyond the scope of this package.I agree with Bart that this is beyond the scope of this package

**Comment by bdestombe** [comment]
Indeed Bart, this is beyond the scope of this package.I agree with Bart that this is beyond the scope of this package
