### ISSUE TITLE
Updating the documentation with the newly published article

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#108]
**Describe the bug**
Updating the documentation with the newly published article. Most likely, it contains better explanations than currently provided in the documentation. The calibration in this package is consistent with what is published in the article.

Are we allowed to copy full sections from the article, given the proper citation? 

**Additional context**
des Tombe, B., Schilperoort, B., & Bakker, M. (2020). Estimation of Temperature and Associated Uncertainty from Fiber-Optic Raman-Spectrum Distributed Temperature Sensing. Sensors, 20(8), 2235. https://doi.org/10.3390/s20082235

**Comment by BSchilperoort** [comment]
Hi Bas, according to Sensors;
```
This is an open access article distributed under the Creative Commons Attribution License which permits unrestricted use, distribution, and reproduction in any medium, provided the original work is properly cited 
```
So copying full sections is not an issue.

**Comment by bdestombe** [comment]
Perfect! I'll have a go at it in two weeks or so.

**Comment by bdestombe** [comment]
And we should add a reference to European Geosciences Union talk of three weeks ago.

**Comment by BSchilperoort** [comment]
Hi Bas. I already uploaded the presentation to this repository. It's in a folder under 'examples', together with the poster from last year.

**Comment by bdestombe** [comment]
Perfect! Sorry, I completely missed that.

**Comment by bdestombe** [comment]
Done!
