### ISSUE TITLE
Check for NaNs matrix X in calibration

### ISSUE THREAD

**Issue by dbrakenhoff** [dtscalibration/python-dts-calibration#112]
**Is your feature request related to a problem? Please describe.**
I am wondering whether it would be nice to have a check for NaNs in the matrix X when attempting to calibrate. One of my reference bath probes didn't quite reach the end of period for which I had DTS data. When I tried to calibrate, it gave me a vague error in scipy lsqr, which I eventually followed back to there being NaNs in my probe data. This took me a while, so I thought maybe it would help to warn the user before the crash and burn inside lsqr.

I saw that there were a bunch of checks already in `wls_sparse` for checking NaNs in the observations, the weights and x0 but not for the matrix X, so I figured why not also check for NaNs there?

**Describe the solution you'd like**
Check for NaNs in the matrix X in `wls_sparse` or some other way.

**Describe alternatives you've considered**
Be a better user, and actually check _all_ your data before attempting calibration.

**Comment by BSchilperoort** [comment]
Thanks for reporting this issue! It's indeed not user friendly, and not the intended functionality.

We can add a routine in the calibration functions where the data of all used sections is checked for invalid values. If any are found a clear error will be raised, so the user will know what to change.

**Comment by BSchilperoort** [comment]
@bdestombe I've added a check for NaN values in a commit (efe36a4724ca68ec49e7cf0e47766f01150a15c1). Additionally we could assert that all values are floating point numbers, do you think that's a good idea or unnecessary?

**Comment by bdestombe** [comment]
Hi David, thanks for your feedback!

@BSchilperoort Do you mean np.isfinite?
```python
np.isfinite([1.0, 1, 4.5, 3, 2, np.nan, np.inf])
Out[6]: array([ True,  True,  True,  True,  True, False, False])
```
Or would you also want to check whether floats are used instead of integers or booleans? Because integers are already silently promoted to floats when converting Celsius to Kelvin (`cal_ref.T.ravel() + 273.15`). 

I would option for implementing `np.isfinite` at the place where you just used `np.isnan`, and also implement it in `wls_sparse` like David suggests. It saves headaches and doesn't cost any time compared to loading data and the least squares routine.
```python
np.isfinite(sparse_matrix.data).any()
```

**Comment by BSchilperoort** [comment]
`np.isfinite` would be better than `np.isnan`. However I meant other data types such as character arrays or `object`.

Without the commit I made, if you change the dtype of e.g. probe1Temperature to `object`, the code would run fine as long as all values of the array are castable to a float dtype.
With the commit I made, it will fail at `np.isnan`, as objects are an invalid dtype there.

It is possible to check if the dtype is any kind of float;
```
if not np.issubdtype(self[key].dtype, np.floating):
    raise ValueError('section data not float')

if not np.any(np.isfinite(self[key].values)):
    raise ValueError('section data has nans/infs')
```

**Comment by bdestombe** [comment]
Ah, now i get it. Yes, sounds good to me.

This reminds me of another thing we should check. I think we should also explicitly check the dimension of the timeseries. It should be the same as the time dimension of the Stokes:
```python
time_dim = self.get_time_dim()
for key in self.sections.keys():
    if self[key].dims != (time_dim,):
        raise ValueError('Time dimension of the reference temperature timeseries {} is not the same as the time dimension of the Stokes measurement. See examples/notebooks/09Import_timeseries.ipynb for more info'.format(key))
```

**Comment by BSchilperoort** [comment]
I've added the checks, including the missing one for wls_sparse. I've also changed all of the checks to np.isfinite. If it passes the CI I'll make a pull request.
