### ISSUE TITLE
Superfluous/non functioning code in calibration_single_ended

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#113]
@bdestombe I was looking through the single-ended calibration routine to add a check for st_var and ast_var (if they're not None if the calibration is wls), and I noticed this block of code. 

As far as I know it does nothing as `i_var` is not used anywhere else. Has this code been superseded or is this a bug? I think it's not functioning and not needed, but I'm just want to be sure.

https://github.com/dtscalibration/python-dts-calibration/blob/c96247bd14e63e4d8cf7b945cb9f134f3a9600df/src/dtscalibration/datastore.py#L1520-L1528

**Comment by bdestombe** [comment]
Yes, there is indeed something wrong with the implementation for single ended.

The idea is to give some flexibility in how to define `st_var`:
- It could be a float, which is what we are currently doing most of the time
- It could be a function with a single argument, which is the intensity.
- An array of the shape `ds.st.shape`, not implemented in single ended nor in double ended. 
- a Dask/xarray object that evaluates to a float or array with `i_var = np.asarray(i_var, dtype=float) `
- An array containing values for locations that are used for calibration. Not implemented in single ended nor in double ended. We maybe should try to avoid this, because it should be defined for `ix_sec` (reference section indices used for calibrating \gamma and \Delta\alpha) and `hix_sec` and 'tix_sec` (indices for the matching temperature sections). Which makes it complicated for everyone.

What has to be done from my point of view, but please let's discuss:
- The code section you referenced should be moved to `calibrate_utils.py/calibration_single_ended_solver()`
- Check that if st_var is an array, it has the same shape as `ds.st.shape`

Does this make any sense?

**Comment by BSchilperoort** [comment]
I'll move and change the code. Only moving won't work as the code is non-functional, as st_var and ast_var are not redefined; their values will be unchanged, e.g.:
```python
st_var = 2
ast_var = 3

for i_var, i_label in zip([st_var, ast_var], ['st', 'ast']):
    i_var = 0

print(st_var, ast_var)
```
will output `2 3`


I also see now that passing a callable st_var will not work for the single_ended_solver at the moment. I'll fix that as well.

**Comment by BSchilperoort** [comment]
Additionally, it is probably good to add tests for all the cases, as these are currently not implemented.

st_var as;
- float (python float, xarray/dask size 1 array)
- callable
- array of size ds.st.shape

**Comment by bdestombe** [comment]
About the line of thought of moving that piece of code around. I think the code was originally in datastore.py/DataStore/calibration_single_ended() and datastore.py/DataStore/calibration_double_ended(). But then thought it would be better keep most arrays as Dask arrays in datastore.py/DataStore. But as the least squares routines require the matrices to be in memory, thus `calibrate_utils.py/calibration_single_ended_solver()` and `calibrate_utils.py/calibration_double_ended_solver()` load all data into the memory.

**Comment by BSchilperoort** [comment]
I've been working on implementing the ideas, however I've encountered a possible issue with using an array as input. Before building up the matrix, in `calibration_single_ended_solver`  and `calibration_double_ended_solver`, the datastore is sorted by x. If the st_var is an array, this is not sorted. Perhaps it is safer to only allow a `DataArray` so there will be no mix-up in the x coordinate?

```python
# get ix_sec argsort so the sections are in order of increasing x
ix_sec = ds.ufunc_per_section(x_indices=True, calc_per='all')
ds_sec = ds.isel(x=ix_sec)
```

**Comment by bdestombe** [comment]
Great that you're fixing these things! If an array is passed to `st_var` with shape that is broadcastable to `ds.st.shape`, I think we can assume it is sorted along the x-dimension and the time-dimension.

The other case, where you'd pass an array to `st_var` that is not broadcastable to `ds.st.shape` but is broadcastable to `ds_sec.st.shape`, is something we'd like to avoid. This case would require indeed some coordinate system, like you are suggesting by using a `DataArray`. Also, we'd separately have to pass `st_var_hix` and `st_var_tix` which would result in complete chaos.

So I don't think we'd need that specified sorting for the different cases:
- float (python float, xarray/dask size 1 array)
- callable
- array of size ds.st.shape

**Comment by BSchilperoort** [comment]
If we can assume that it is sorted along the x- and time-dimensions, why do we sort the DataStore at the start of the solver functions? I think the danger is that the st_var is not sorted (e.g. if the user calculates it based on data from their DataStore), while the datastore does get sorted.

If the user has to provide a `DataArray` that covers the entire `x` and `time` dimensions of `ds.st`, we do not have to separately pass `st_var_hix` and `st_var_tix`; this `DataArray` would be the same data as the (numpy) array of size ds.st.shape, but with dimensions and coordinates to ensure no mix-ups occur.

Making the different cases;

- float (python float, xarray/dask size 1 array)
- callable
- DataArray with coordinates matching ds.st

**Comment by bdestombe** [comment]
Something like the following should work right?
```python
# https://stackoverflow.com/questions/24743753/test-if-an-array-is-broadcastable-to-a-shape
def is_broadcastable(shp1, shp2):
    for a, b in zip(shp1[::-1], shp2[::-1]):
        if a == 1 or b == 1 or a == b:
            pass
        else:
            return False
    return True

if callable(st_var):
    ix_sec = self.ufunc_per_section(x_indices=True, calc_per='all') 
    i_var = i_var(self[i_label].isel(x=ix_sec)).values 
elif is_broadcastable(st_var.shape, ds.st.shape):
    i_var = np.asarray(i_var, dtype=float)
else:
    raise MajorError
```

**Comment by bdestombe** [comment]
"If we can assume that it is sorted along the x- and time-dimensions, why do we sort the DataStore at the start of the solver functions?"
It is not meant for sorting, but to select the x-indices that are in calibration baths. `ds_sec` is usually much smaller than `ds`.

**Comment by bdestombe** [comment]
Wait, I made a small error in the previous suggested code
```python
# https://stackoverflow.com/questions/24743753/test-if-an-array-is-broadcastable-to-a-shape
def is_broadcastable(shp1, shp2):
    for a, b in zip(shp1[::-1], shp2[::-1]):
        if a == 1 or b == 1 or a == b:
            pass
        else:
            return False
    return True

if callable(st_var):
    ix_sec = self.ufunc_per_section(x_indices=True, calc_per='all') 
    i_var = i_var(self[i_label].isel(x=ix_sec)).values 
elif is_broadcastable(st_var.shape, ds.st.shape):
    if st_var.shape == ds.st.shape:
        i_var = np.asarray(st_var[:, ix_sec], dtype=float)  # not sure if DataArray supports fancy indexing with numpy arrays
    else:
        i_var = np.asarray(i_var, dtype=float)

else:
    raise MajorError
```

**Comment by BSchilperoort** [comment]
Sorry for the confusion, I mixed up things in my head about the sorting. I have now figured out how I can implement it.

The following function will check and parse the st_var inputs. As this bit of code is repeated multiple times I made it a separate function in `calibrate_utils.py`. It's usable for both single- and double-ended calibration. With the `ix_sel` kwarg the selection can be made for either the reference sections or the matching sections.

It supports all of;

- float (python float, xarray/dask size 1 array)
- callable
- array-like which is broadcastable to ds.st (both x & time, or only one of either)

```python
def parse_st_var(ds, st_var, st_label='st', ix_sel=None):
    if callable(st_var):
        st_var_sec = st_var(ds[st_label].isel(x=ix_sel).values)

    elif np.size(st_var) > 1:
        if ix_sel is None:
            raise ValueError(
                '`ix_sel` kwarg not defined while `st_var` is array-like')

        for a, b in zip(st_var.shape[::-1], ds[st_label].shape[::-1]):
            if a == 1 or b == 1 or a == b:
                pass
            else:
                raise ValueError(
                    st_label + '_var is not broadcastable to ds.' +
                    st_label)

        x_dim = ds[st_label].dims.index('x')
        if x_dim == 0 and len(st_var.shape) > 1:
            st_var_sec = np.asarray(st_var, dtype=float)[ix_sel]
        elif x_dim == 1 and st_var.shape[1] > 1:
            st_var_sec = np.asarray(st_var, dtype=float)[ix_sel]
        else:
            st_var_sec = np.asarray(st_var, dtype=float)

    else:
        st_var_sec = np.asarray(st_var, dtype=float)

    assert not np.any(~np.isfinite(st_var_sec)), \
        'NaN/inf values detected in ' + st_label + '_var. Please check input.'

    return st_var_sec
```

**Comment by bdestombe** [comment]
Woow! That looks really advanced!

A small comment, the index of the x-dimension is fixed, we check for that at https://github.com/dtscalibration/python-dts-calibration/blob/c96247bd14e63e4d8cf7b945cb9f134f3a9600df/src/dtscalibration/datastore.py#L1489
==> `x_dim` is always `0`.

And, if `ds.st` happens to be a chunked Dask array, the following is a bit nicer:
```python
st_var_sec = st_var(ds[st_label].isel(x=ix_sel).values)
```
change it to:
```python
st_var_sec = st_var(ds[st_label].isel(x=ix_sel)).values
```
This way `st_var` evaluates also in chunks.

**Comment by BSchilperoort** [comment]
The fixed x dim makes it a lot easier. Thanks for the suggestions.

**Comment by bdestombe** [comment]
But this was indeed a stupid mistake of me. Good catch!
```python
st_var = 2
ast_var = 3

for i_var, i_label in zip([st_var, ast_var], ['st', 'ast']):
    i_var = 0

print(st_var, ast_var)
```

**Comment by klapo** [comment]
The check for the variances not being `None` broke using the single-ended wls method as I had constructed it for pyfocs. What happened previously, before the wls method asserted that the variances were not None? Specifically, do I need to re-run the calibration with the estimated variances provided?

**Comment by BSchilperoort** [comment]
Hi Karl, after digging through the v1.0.0 code it seems that not passing `st_var` caused all weights to be set to 1 in `calibration_single_ended_solver`; this means that the calibrations you ran were effectively OLS. If you want a WLS calibration with accurate confidence intervals I'm afraid you will have to re-run the calibration. I'm sorry for the inconvenience caused!

The estimations for the stokes/anti-stokes variance are very important and non-trivial if you want to determine the uncertainty of the temperature estimate. For short lengths of fiber (where the range of signal strength is small) a constant variance is sufficient, but with longer setups the variance will have to scale with the signal strength. I think this is insufficiently explained in the notebooks at the moment.

**Comment by klapo** [comment]
Hi Bart, thanks for the quick feedback! Not a problem that we were doing an ols method -- I'm just happy to know what we have.

Part of the reason I didn't notice the impact this had on uncertainty is because, I've been well... uncertain on how to use them for our purposes. We have temperature perturbations that vary in both their temporal and spatial scales so it isn't clear to me which way of characterizing uncertainty method is best suited for that. Any words of advice? I'm also happy to move the conversation out of this issue to a more appropriate place.

**Comment by bdestombe** [comment]
Hi Both,
I don't think there was an impact, given it didn't crash.
- If `st_var` was a float, it would still be the same float after this superfluous code.
- If `st_var` was a Dask array the calibration would have been really slow, as it would re-compute the Dask array for every usage.
- If it would have been a function, it would have crashed and Karl would have noticed.
- Numpy arrays would have been okay, but there would not be any checks on the shape.

Right?

**Comment by klapo** [comment]
Hi Bas,

I wasn't providing an argument for `st_var` in the single-ended calibrations. I just had
```
dstore.calibration_single_ended(
    method=method)
```
In version 1.0.0 this structure doesn't cause an error so I was blissfully unaware of what effect that decision had.  In version 1.0.1 this approach triggers the assert statement for `st_var` being `None`

**Comment by BSchilperoort** [comment]
The issue was in this part of the code

https://github.com/dtscalibration/python-dts-calibration/blob/10c7bece1c380a800b26f7b3add37c7cfdc3aba4/src/dtscalibration/calibrate_utils.py#L221-L237

Whether it's a WLS or OLS calibration was not passed to `single_ended_solver`. If the `st_var` was `None` it just set the weights to `1.`.

**Comment by bdestombe** [comment]
Ah I see! Thanks for clearing this one out.
