### ISSUE TITLE
Notebook 04 on stokes variance is outdated

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#120]
Since the addition of the different types of estimations of the stokes variance (constant/exponential/linear) the notebook on providing signal variance estimates for the calibration remained unchanged.

I think it has to be updated and clearly explain the differences, and give advice to the users for which estimation to pick.

**Comment by klapo** [comment]
Ha! I was just about to ask a question regarding this.

As I am adding stokes/anti-stokes variances to the wls single-ended calibration I am getting an error. My dataset looks like this:
```
<dtscalibration.DataStore>
Sections:
    coldProbe              ( -0.49 +/- 0.01°C)	22.20 - 24.45 and 640.35 - 642.20
    warmProbe              ( 36.04 +/- 0.00°C)	16.90 - 18.90 and 645.50 - 647.75
Dimensions:              (time: 8, x: 2577)
Coordinates:
  * x                    (x) float64 0.06679 0.321 0.5752 ... 654.4 654.6 654.9
  * time                 (time) datetime64[ns] 2019-07-22T03:18:36 ... 2019-07-22T03:19:58
Data variables:
    st                   (x, time) float64 ...
    ast                  (x, time) float64 ...
    tmp                  (x, time) float64 22.91 23.03 23.06 ... 13.59 13.73
    warmProbe            (time) float64 ...
    coldProbe            (time) float64 ...
    userAcquisitionTime  (time) timedelta64[ns] 00:00:01 00:00:01 ... 00:00:01
Attributes:
    LAF_beg:             0.0667928
    LAF_end:             654.884
    dLAF:                0.254
    calibration_method:  wls single
    _sections:           coldProbe:\n- !!python/object/apply:builtins.slice\n...
    isDoubleEnded:       0
```
and when running:
```
st_var, resid = single.variance_stokes(st_label='st')
```
I get the following error:
```
Traceback (most recent call last):
  File "/Users/karllapo/anaconda3/bin/PyFOX.py", line 219, in <module>
    dstore = pyfocs.single_calibrate(dstore, method=method)
  File "/Users/karllapo/anaconda3/lib/python3.7/site-packages/pyfocs/data.py", line 216, in single_calibrate
    st_var, resid = single.variance_stokes(st_label='st')
  File "/Users/karllapo/anaconda3/lib/python3.7/site-packages/dtscalibration/datastore.py", line 926, in variance_stokes
    return self.variance_stokes_constant(*args, **kwargs)
  File "/Users/karllapo/anaconda3/lib/python3.7/site-packages/dtscalibration/datastore.py", line 1049, in variance_stokes_constant
    check_timestep_allclose(self, eps=0.01)
  File "/Users/karllapo/anaconda3/lib/python3.7/site-packages/dtscalibration/datastore_utils.py", line 81, in check_timestep_allclose
    dt = ds[dim].data
  File "/Users/karllapo/anaconda3/lib/python3.7/site-packages/xarray/core/dataset.py", line 1254, in __getitem__
    return self._construct_dataarray(key)
  File "/Users/karllapo/anaconda3/lib/python3.7/site-packages/xarray/core/dataset.py", line 1167, in _construct_dataarray
    self._variables, name, self._level_coords, self.dims
  File "/Users/karllapo/anaconda3/lib/python3.7/site-packages/xarray/core/dataset.py", line 167, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'userAcquisitionTimeFW'
```

I am on dtscalibration v1.0.2 and was following the example posted in the notebook. So two questions:
1) Based on the DataStore object I posted, did I do something wrong converting between the pyfocs/DataStore formats? Specifically, should single-ended methods have the `userAcquisitionTime` be called `userAcquisitionTimeFW`?
2) For five minute chunks and time steps between 1s-10s that we typically use, is the constant, exponential, or linear method the best default choice?

**Comment by BSchilperoort** [comment]
1. I believe it should be called `userAcquisitionTimeFW` I think this is then also not correctly documented yet... It is mainly required to ensure that all measurements have the same acquisition time, to avoid mix-ups. If you already take care of this in pyfocs, you can just create a variable with a uniform value, e.g. '1.0', with dimension `time`.

2. It's more related to your range in signal strength. If you have a fiber that's longer than 200 - 300 m, you probably need to use the linear method. The linear method allows a signal variance dependent on the signal strength. For the Silixa and Sensornet devices we found that this is a linear relation, which (approximately) goes through the origin; i.e. at 0 Stokes intensity, the signal variance is very close to 0.
With this assumption you need less data to accurately determine the variance. What's most important for a good fit is the number of measurements rather than the acquisition time. With the `variance_stokes_linear` method you can tell it it to plot the result, you can check this to see how many measurements you need. I expect 5 minutes at 1s acq time to be sufficient, as that gives you 300 measurements. However, 30 measurements might be a bit too few.

**Comment by klapo** [comment]
1. Previously I had `userAcquisitiontime` set to a vector with a constant value as you described for single-ended cases. I took a similar approach for `userAcquisitiontimeFW` in the double-ended cases. I've updated our code that handles the conversion between data formats.
2. I think for now we will implement the constant method, but it is on my to do list to allow for other options.

**Comment by bdestombe** [comment]
Since we now support full arrays of `st_var`, it is possible to account for varying acquisition times by linearly scaling the variance inversely with the acquisition time. 

The reason why we explicitly to decide avoid varying acquisition times, is that it results in a lot of extra code and exceptions, while most our measurements were at a single acquisition time. And to account for the few times that they did vary, it was sufficient to treat them as separate calibration instances.

The methods to estimate the variance in the Stokes are not so easy to modify to support varying acquisition times.
