### ISSUE TITLE
Change in userAcquisitionTimeFW after DTS malfunction

### ISSUE THREAD

**Issue by johannespopma** [dtscalibration/python-dts-calibration#123]
I am reading oryx data by using the sensornet function.
Due to a malfunction in de DTS system there is a gap in the data for about an hour.
When I am trying to calibrate the data I receive the error:

Assertionerror: Acquisition in Forward channel not equal for all time steps.

When I look at the data I indeed see that the userAcquisitiontimeFW changed after the malfunction:

![image](https://user-images.githubusercontent.com/40393346/84362863-2e806300-abce-11ea-929a-0bc6a71fdf31.png)

How to handle this change in data in the calibration?

**Comment by BSchilperoort** [comment]
Hi Johannes,

The constant acquisition time is (at the moment) required to properly calculate the signal uncertainty. I think you can run the OLS calibration without issues. 
However, if you want to do a weighted calibration and/or know the temperature uncertainty, you will have to split the data up in two parts and calibrate them separately.

E.g. 
```python
ds0 = ds.sel(time=slice(None, '2020-06-09T22:00'))
ds1 = ds.sel(time=slice('2020-06-09T22:00', None))
```

**Comment by bdestombe** [comment]
Hi Johannes,
Thanks for reaching out. I think Bart's second suggestion would be most promising.

- Split the `DataStore` in two, like Bart suggests.
- Calibrate the two `DataStore`s separately following the steps of the example notebook 7 or 8.
- Merge the two `DataStore`s with 

```python
from dtscalibration import open_datastore
import xarray as xr


# combine and write to disk
ds = xr.combine_by_coords([ds0, ds1])
ds.to_netcdf('file.nc')

# load from disk
ds = open_datastore('file.nc')
```

http://xarray.pydata.org/en/stable/generated/xarray.combine_by_coords.html#xarray.combine_by_coords

Good luck!

**Comment by bdestombe** [comment]
In addition to the suggestions listed above, you could fix the parameters during the second calibration instance with the parameters from the first calibration instance. By using the `fix_gamma=(ds0.gamma.values, ds0.gamma_var.values`) and `fix_alpha=(ds0.alpha.values, ds0.alpha_var.values)` arguments when calling the calibration function for the second calibration instance.

See notebook 13

**Comment by BSchilperoort** [comment]
I assume the problem has been solved. If it's not please re-open the issue.
