### ISSUE TITLE
Storing matching indices

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#127]
**Is your feature request related to a problem? Please describe.**
The matching indices are not stored in the DataStore. Currently, you can store your datastore as netCDF and you could almost repeat your calibration with the data stored in the object. Except for: matching sections, and the variances.

**Describe the solution you'd like**
Store the matching_indices (a list of tuples, containing the indices of two locations that have the same temperature) in the DataStore as a DataArray with a single dimension `'x'`. It contains ints, that refer to locations to which they match.

For locations that are not part of matching sections, the index reflects its own index (as NaN's are not possible for integers)

**Comment by BSchilperoort** [comment]
This sounds like a good idea. Especially as the other calibration settings are stored (sections, trans_att).

However, why not store it in the same way sections are stored? I.e., the dictionary with the slice mapping. An array of integers representing a mapping to other locations isn't easily human readable.

As for not being able to add NaN's, you can just use a set integer value to represent NaN, e.g., `-1`.
Don't forget that overlapping matching sections might be difficult to turn into an array representation of matching indices!

**Comment by bdestombe** [comment]
Good suggestion. That indeed makes sense, to store it like the sections property, with a `'_sections'` attribute. Let's go that route.

**Comment by BSchilperoort** [comment]
Fixed by #204
