### ISSUE TITLE
ORYX F/W v4

### ISSUE THREAD

**Issue by mankoff** [dtscalibration/python-dts-calibration#129]
I'm trying to use this package with "ORYX F/W v4" data and your package reports that it is untested. I'm waiting to upload sample data until I have permission to share it. Opening issue anyway...

**Comment by BSchilperoort** [comment]
Hi Ken, as we do not have access to all versions of all machines the package reports if the datatype is familiar (e.g. a .ddf file), but has not been tested and as such we can not ensure that the data has been read correctly.

We have tested the following Sensornet data formats:
- 'Halo DTS v1'
- 'ORYX F/W v1,02 Oryx Data Collector v3'
- 'ORYX F/W v4,00 Oryx Data Collector v3'

It would be great if you could share a sample file (a single one suffices). It is also possible to remove or anonymize any identifiers you do not want to share, e.g. the machine serial number or the installation name.

**Comment by mankoff** [comment]
If you've tested `'ORYX F/W v4,00 Oryx Data Collector v3'` this should be easy because the `cfg` file reports `Software version number:	ORYX F/W v4.00 Oryx Data Collector v3.7.3`.

Here is a sample taken with a mini-bend turn-around at the end of the cable.
[channel 1 20190110 182312 00001.ddf.zip](https://github.com/dtscalibration/python-dts-calibration/files/4915321/channel.1.20190110.182312.00001.ddf.zip)

**Comment by BSchilperoort** [comment]
It seems that the version string depends on the localization settings of the data collection PC. The .ddf files we've looked at have mostly had comma separated data values, it's very strange that the version string changes as well.

I have made a change in how the Sensornet versions are checked (ceb7491), and tested it on your file. It looks like it is working perfectly now. If you install the development version of the package you should be able to load in your data without any warnings.

The valid versions are now;
- `'Halo DTS v1*'`
- `'ORYX F/W v1.02 Oryx Data Collector v3*'`
- `'ORYX F/W v4.00 Oryx Data Collector v3*'`
Where `*` is a wildcard.

**Comment by mankoff** [comment]
How do you recommend I convert the sample file here to the double-ended measurement that it actually is? The `read` function reports `The measurement is single ended`, but it is not. Should I manually detect the turn-around location, split with a slice on `x`, manually reset and reverse the `x` coordinate so that it appears that I have two single-ended measurements, and then combine as per your tutorial here dhttps://python-dts-calibration.readthedocs.io/en/latest/examples/notebooks/11Merge_single_measurements_into_double.ipynb.html ? Or would you suggest some other workflow?

**Comment by BSchilperoort** [comment]
The file you uploaded here is single ended; there is no data in there but the forward Stokes and anti-Stokes measurements . Did you set up the Oryx to measure two different channels? If so you can indeed follow the tutorial of notebook 11.
