### ISSUE TITLE
Which GitHub site?

### ISSUE THREAD

**Issue by mankoff** [dtscalibration/python-dts-calibration#131]
I've found both this site and https://github.com/bdestombe/python-dts-calibration and it isn't clear which is "official". I suggest a more clear redirect from the secondary to the primary source.

**Comment by BSchilperoort** [comment]
I'm afraid this is a feature of git we can not influence; people can make a 'fork' of a repository. You can see if something is a fork here:
![image](https://user-images.githubusercontent.com/12114825/87293749-0bb1d900-c503-11ea-8200-580fbc2519d6.png)

As you forked the repository as well, it looks the same on your github page: https://github.com/mankoff/python-dts-calibration

**Comment by mankoff** [comment]
I know how GitHub works, and I've made my own fork (so I can contribute! :). But the fork I mentioned here seems to be from one of the authors of the project, which is why it is a bit more confusing. That's the issue. But if this is the official site, I'll stay here...

**Comment by BSchilperoort** [comment]
Yes, this is the official site (as it's not a fork). You can see the structure here: https://github.com/dtscalibration/python-dts-calibration/network/members
It would perhaps be better if github showed a bit more clearly that a user is looking at a fork, but we can't do anything about that!

We as authors also work in our own forks of the project, especially when it's a larger modification to the library.
