### ISSUE TITLE
stokes variance; fit through zero?

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#134]
Recently we have gained new results from measurements with a Silixa Utima-M unit, where we used a 5 km long fiber. This allows us to have a large range of signal intensities (200 - 5000 units).

The image below shows the intensity-variance relationship found using `stokes_variance_linear`. As we set up a double-ended measurement we are able to use the internal reference coils for determining the signal variance.
![image](https://user-images.githubusercontent.com/12114825/117663732-488d4180-b1a1-11eb-9ac5-512c56c348d5.png)

It seems like (at least with this machine), the intercept is at ~2, instead of 0. It might be better to not make fitting through 0 the default, or at least provide a good amount more documentation/write a short white paper on the stokes intensity-variance relationship and its importance for determining the temperature variance or uncertainty bounds.

**Comment by bdestombe** [comment]
Another nice find, Bart! These finds really improve the calibration procedure.

So we should change the default value for `through_zero` to `False`?

Should we also check that the curve fit returns a positive value for `a` and `b` in `st_var = a * ds.st + b`?

**Comment by zrxdaly** [comment]
Recently I am calibrating a 800m cable. Due to high intensity signal and relative small variance, with the setting `through_zero=False`, the intecept sometimes goes to negative (). In this case, is it better just set `through_zero=True`, right?

`slope, offset: (0.0005024105845405379, -0.42438217912320964)`
![example](https://user-images.githubusercontent.com/37229869/192108493-1a506269-61a2-4c8a-bb3b-d3840221d5d1.png)

**Comment by BSchilperoort** [comment]
Perhaps with `through_zero` you would get more accurate results here, yes. 

Additionally, if you remove the points in this image your result is probably more accurate, as it seems that both sections have a **U** shape; a characteristic of when you are not conservative enough with your bath/section selection.
![image](https://user-images.githubusercontent.com/12114825/192149516-4f5f4708-86d5-4be2-b08c-6aa3df9f4a13.png)

For the most accurate results an extra section at very low Stokes intensity would of course be ideal.

**Comment by zrxdaly** [comment]
> Perhaps with `through_zero` you would get more accurate results here, yes.
> 
> Additionally, if you remove the points in this image your result is probably more accurate, as it seems that both sections have a **U** shape; a characteristic of when you are not conservative enough with your bath/section selection. ![image](https://user-images.githubusercontent.com/12114825/192149516-4f5f4708-86d5-4be2-b08c-6aa3df9f4a13.png)
> 
> For the most accurate results an extra section at very low Stokes intensity would of course be ideal.

Nice! Thanks for the tips. Very helpful!
