### ISSUE TITLE
Issues calibrating long fiber; bias in calibration baths

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#136]
We have recently measured a long fiber optic cable, +-4500 m in length. It was one continuous fiber without any splices.
There is some light strain concentrations in a few locations, but no major drops in signal strength.

Below is an image of the stokes and reverse-stokes data
![image](https://user-images.githubusercontent.com/12114825/117948734-b6587b00-b311-11eb-98c3-cbec8e16d9e2.png)

For calibration two very well mixed water baths were used (of two different temperatures). One spool of fiber was put in a bath near the beginning of the cable, and a spool of fiber was put into each bath near the end of the fiber.
Data was calibrated double-ended using wls, with the two spools near the end of the fiber for reference.

Below is the result showing the temperature residuals (tmpw). In all baths a bias is visible. The bias is lowest in the validation bath (6>16 m) than in the calibration baths (?!).
![image](https://user-images.githubusercontent.com/12114825/117949397-60d09e00-b312-11eb-93a4-b2cf72a68165.png)

No (mean) temperature difference exists between the calibrated forward and backward temperatures.

When calibrating using only the (6, 16) section for calibration, and fixing gamma at 485., the resulting parameter (and thus biases) are exactly the same.

Of course this is quite puzzling to me. As of now I have some possible theories;

- Incorrect Pt100 data (eg. wrongly calibrated)
- Slight strain on fiber has an unaccounted for asymmetric(?) effect
- With the large differences in stokes intensity over the length of fiber (2500 to 200 units), any inaccuracies in the calibration/linearity of the stokes detectors will cause an inaccurate calibrated temperature.

**Comment by BSchilperoort** [comment]
About the stokes detector inaccuracy; by this I mean that the real stokes signal != detector reported signal.

What I have regularly observed at the end of a stokes trace is the following behavior;
![image](https://user-images.githubusercontent.com/12114825/117952165-30d6ca00-b315-11eb-88e5-7310f7761bc3.png)
After the end of the fiber (either internally, or terminating at a connector), the signal intensity drops _below_ zero, before approaching zero asymptotically. Is this due some other effect, or could it point towards limitations in detector accuracy?

**Comment by klapo** [comment]
Hi Bart,
A potential additional cause may be poorly constrained differential attenuation. We've noticed in the past that strain on the fiber can make it difficult to get a good calibration. Associated with this strain were changes in the slope of log(Ps) and log(Pas) (and thus differential attenuation, degrading the calibration quality). Nominally, the double-ended method should be able to resolve these differences and bend losses should only be step losses. But, we have not found that to be the case in several of our experiments.

This is a lot of exposition for asking: Would it be worthwhile to check the modeled vs an estimate of the actual differential attenuation at a given location?
