### ISSUE TITLE
Inconsistent ds.sections behavior

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#138]
The sections for calibration can be set with with the command `ds.sections = {~}`. This sets the sections for calibration.
When running `ds.calibration_double_ended`, and providing the `sections` kwarg, the `ds.sections` data is changed to match, which is quite logical, with `ds` being changed in-place.
(Changing ds inplace by default as opposed to returning a new object is of course also a possible point of contention...)

However, there is inconsistent behavior in some functions;
`ds.temperature_residuals` does _not_ change `ds.sections`
`ds.variance_stokes_linear` does change `ds.sections`
Especially as the Stokes variances do not need to be calculated from sections at a known temperature (internal reference is perfect for this), I am a bit puzzled why the `ds.sections` is quietly changed.

I would propose to only change `ds.sections` manually or by `ds.calibration_*_ended`. Or even deprecate setting `ds.sections`, and forcing the specification every time to reduce possible user errors.

**Comment by bdestombe** [comment]
That must have been an annoying bug to trace! Great find!

Yes, great suggestions. I would be in favour of requiring passing a `sections` argument with each of the `ds.calibration_*_ended()` functions, like you proposed. It would be these functions that can set `ds.sections`. This way the calibration results and the `sections` object stay in sync, even when writing the `ds` object to a netCDF file.

**Comment by bdestombe** [comment]
The advantage here was to have the sections stored in the netcdf, such that after loading from file the reference sections were loaded as well.

Thus we allow sections to be an argument of all these functions and only store sections when using the `ds.calibration_*_ended()` functions? And all other functions require `sections` as a kwarg and will not use `ds.sections`?
