### ISSUE TITLE
variance_stokes_linear not working

### ISSUE THREAD

**Issue by mitchelljbrown** [dtscalibration/python-dts-calibration#139]
I am dealing with a double ended Silixa DTS system that is around 200m in cable length. When I try and calculate the variance of the stokes signal with "variance_stokes_linear", I am greeted with the error "too many values to unpack: expected 2". "variance_stokes_constant" still works.

Originally I thought this was a problem with my data but when I tried to use the linear function to calculate variance in the example notebooks the same error occurred. Could there be an issue with the function or am I missing something. 

Thanks for any and all help.

**Comment by BSchilperoort** [comment]
Hi Mitchell,

I think this issue originates from the fact that `variance_stokes_constant` returns 2 variables, while `variance_stokes_linear` returns 6. This means it's not as easy as just replacing the function name.

The function `variance_stokes_linear` returns: `slope, offset, st_sort_mean, st_sort_var, resid, var_fun`. You can pass `var_fun` to the calibration routine as described [here ](https://github.com/dtscalibration/python-dts-calibration/blob/8dd7b040a80568f91c2cff4e764c858c0deb13e3/src/dtscalibration/datastore.py#L2482)

The doc string of  `variance_stokes_linear` seems to be missing some information, so I understand your confusion.

I recently wrote [this document](https://github.com/dtscalibration/python-dts-calibration/blob/master/examples/temperature_variance_from_stokes.pdf) lining out the workings of the linear Stokes intensity--variance relationship. It contains a few practical tips as well so I would recommend you to read it.

Best regards,
Bart

**Comment by bdestombe** [comment]
Hi Mitchell,
Did you manage to resolve your issue with the help of Bart? If not, feel free to reopen this issue with a snippet of your code.

Ciao,
Bas

**Comment by mitchelljbrown** [comment]
Hi Bas,

Sorry for the late response. Thank you for replying to my issue. I am
relatively new to programming and have recently been interested as I am
working with A-DTS for my MSc thesis. I will look into this today and get
back to you. The variance_stokes_function has been taking all day to run as
the datasets I am working with consist of roughly 7000 .xml files so
hopefully I can get back to you in a timely manner.

Thanks,

Mitchell
