### ISSUE TITLE
some problems with resid.plot,ds.tmpw.plot and ds.calibration_double_ended(method=wls)

### ISSUE THREAD

**Issue by Roywu99** [dtscalibration/python-dts-calibration#140]
I am dealing with a double ended Silixa DTS system that is around 700m in cable length.When I try and plot residual with "resid.plot",I am greeted with the error "The input coordinate is not sorted in increasing order along axis 0. This can lead to unexpected results. Consider calling the `sortby` method on the input DataArray. To plot data with categorical axes, consider using the `heatmap` function from the `seaborn` statistical plotting library"."The same error is encountered when using ds.tmpw.plot.

another problem is using ds.calibration_double_ended(method=wls) to calibrate, I am greeted with the error "operands could not be broadcast together with shapes (5508,78) (41,)"

I don't no how to deal with these problems.
Thanks for any and all help.

**Comment by BSchilperoort** [comment]
Hi, if you have not solved this issue by yourself yet, could you show me the output of `print(ds)`?

**Comment by Roywu99** [comment]
Hi, these photos are the output of print(ds)
![printds1](https://user-images.githubusercontent.com/89886829/132706309-6f7fed69-e857-4117-81c9-f2de5d6bd4c7.PNG)
![printds2](https://user-images.githubusercontent.com/89886829/132706323-7bc496bd-af89-4daf-b43f-75b9b1d30538.PNG)

**Comment by bdestombe** [comment]
Hi @Roywu99 , I am not sure what went wrong and is hard to judge without a bit more context. The package has changed a lot over time, including the big re-write currently in #204 . Im closing the issue, but feel free to reopen the issue if is still relevant.
