### ISSUE TITLE
Move to quantile regression instead of Monte Carlo to estimate confidence intervals

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#141]
**Is your feature request related to a problem? Please describe.**
Monte Carlo sampling is super computational intensive.

**Describe alternatives you've considered**
The field of quantile regression may introduce a possible way to circumvent the MC sampling. https://pubs.aeaweb.org/doi/pdf/10.1257/jep.15.4.143

**Comment by BSchilperoort** [comment]
Hi Bas, sounds good if it can reduce the computational power from MC sampling. I think that generally users (including me) choose to use a too low MC sample count as it takes too long!

**Comment by bdestombe** [comment]
https://stackoverflow.com/questions/35185046/using-statsmodels-to-plot-quantile-regression-for-2nd-order-polynomial

This could work

**Comment by bdestombe** [comment]
This idea was tested and didn't work as nicely as the alternative approach of #157
