### ISSUE TITLE
Tests for py36, py37 not working. Deprecate?

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#142]
Travis has lately not been successfully running the builds. In my effort to fix this I found out that these problems concentrated in the Python 3.6 and 3.7 versions. In the `travis_fix` branch, I updated the default version for the check, docs etc. to 3.9 and it [seems to run fine](https://app.travis-ci.com/github/dtscalibration/python-dts-calibration/builds/247265799). Python 3.8 also still runs without issues.

Seeing as 3.6 has reached its end of life, and 3.7 is also on its way out, shall we bump the package to a new version and drop support for 3.6 and 3.7? @bdestombe

**Comment by bdestombe** [comment]
Great findings, Bart! Given our limited time to develop, I agree with you that we should move forward and drop the support for the nagging legacy Python versions. 
Maybe we can add a suggestion to try to install the package to other Python versions, at their own risk, by overruling the Python versions that are required via setup.py during installation?
