### ISSUE TITLE
Read silixa ultima xml

### ISSUE THREAD

**Issue by mariosgeo** [dtscalibration/python-dts-calibration#145]
Hi,

Reading the xml files (see attached file, rename it to xml) from silixa ultima, fail. Could you add support this?

The error message is ParseError: not well-formed (invalid token): line 1, column 0

[channel 2_20220429182758453.txt](https://github.com/dtscalibration/python-dts-calibration/files/9120238/channel.2_20220429182758453.txt)

**Comment by BSchilperoort** [comment]
I am afraid I cannot reproduce this bug. For me the file loads perfectly fine on a clean install of dtscalibration.

Try installing the in-dev version of the library:
`pip install https://github.com/dtscalibration/python-dts-calibration/zipball/master --upgrade`

**Comment by mariosgeo** [comment]
Thanks for the reply. I confirm that the -dev version works.

**Comment by mariosgeo** [comment]
After all the error is coming from dask. I am reading 30k of those files, so in file 
io.py, line 736
    ts_arr = da.stack(ts_lst).compute()
I run out of memory (no error message, I just watch the task manager).

Any solution to read the files in batches?

**Comment by BSchilperoort** [comment]
I would recommend splitting the calibration up in chunks, instead of trying to calibrate everything at once.

You can load all the files into a list or numpy array, and then split that in chunks of a more reasonable size where all the xml files fit in memory. Then try to do the whole _loading -> calibration -> save to netCDF_ routine per batch.

**Comment by mariosgeo** [comment]
Thanks again. I will do so. 
Just from curiosity, I though dask could handle big data stored in hard drive and not in memory. Oh well...

**Comment by BSchilperoort** [comment]
It could work if you convert the loaded in xml files to netCDF in batches first, and then load the netcdf files into xarray with open_mfdataset.

However, dask can be quite slow if you run it on your local machine (compared to doing the calculations with everything in-memory), and you can probably calibrate just fine with only parts of the total data set.

**Comment by mariosgeo** [comment]
That is the solution I will follow. Thanks again.
To explain why I want "large"datasets, it due to my setup. I observe why too much noise on the data, and trying to figure it out what is happing. Data are collected every 1 min, in an environment that I expect changes every 1-2 hours. Thus, measures nearby in space and time should not differ that much. In other words, I want to do some short of calibration ALSO over time, if that makes sense....

**Comment by BSchilperoort** [comment]
I get your problem. There is a different grouping method you can also use, and that is grouping by every n-th index;
```py
step = 10
for i in range(step):
    subset_files = all_files[i::step]
    # do calibration
```
This would ensure that your calibration data is well spread-out over time.

When all the data is calibrated, you can reduce your temporal resolution with .resample, this should also reduce your measurement noise.
