### ISSUE TITLE
local variable 'flip_reverse_measurements' referenced before assignment

### ISSUE THREAD

**Issue by sdattri** [dtscalibration/python-dts-calibration#150]
File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dtscalibration/datastore.py:5774, in read_sensornet_files(filepathlist, directory, file_ext, timezone_netcdf, timezone_input_files, silent, add_internal_fiber_length, fiber_length, **kwargs)
   5760 else:
   5761     warnings.warn(
   5762         'Sensornet .dff version '
   5763         '"{0}"'.format(ddf_version)
   5764         + ' has not been tested.\nPlease open an issue on github'
   5765         + ' and provide an example file')
   5767 data_vars, coords, attrs = read_sensornet_files_routine_v3(
   5768     filepathlist,
   5769     timezone_netcdf=timezone_netcdf,
   5770     timezone_input_files=timezone_input_files,
   5771     silent=silent,
   5772     add_internal_fiber_length=add_internal_fiber_length,
   5773     fiber_length=fiber_length,
-> 5774     flip_reverse_measurements=flip_reverse_measurements)
   5776 ds = DataStore(data_vars=data_vars, coords=coords, attrs=attrs, **kwargs)
   5777 return ds

UnboundLocalError: local variable 'flip_reverse_measurements' referenced before assignment

This is an issue with my sensornet files.

**Comment by BSchilperoort** [comment]
Hi, I think this is an issue related to the PyPI version being old. The code I see there is missing a line at line 5761 (compared to the current version).

If you install the in-dev version this error should not be there:
`pip install https://github.com/dtscalibration/python-dts-calibration/zipball/master --upgrade`

Not however, that it seems like you're using a file format that has not been explicitly tested. Could you provide us with an example file (double-ended) so we can validate it?

**Comment by sdattri** [comment]
@BSchilperoort How can I provide you with the example file?

**Comment by sdattri** [comment]
@BSchilperoort Also, I am not 100% sure its double ended. Is there a different method for single ended?

**Comment by sdattri** [comment]
[Uploading 1.zip…]()

Here is the attached file for your reference.

**Comment by sdattri** [comment]
[Archive.zip](https://github.com/dtscalibration/python-dts-calibration/files/9638162/Archive.zip)

Here are the example files for your reference. Thanks a lot in advance.

**Comment by sdattri** [comment]
@BSchilperoort I am not 100% sure its double ended. Is there a different method for single ended? Here is a sample file for your reference. Thanks in advance. 
[Archive.zip](https://github.com/dtscalibration/python-dts-calibration/files/9638168/Archive.zip)

**Comment by BSchilperoort** [comment]
Currently I have the following example working on my machine, using the most recent version of dtscalibration (v.1.1.0);

```py
from glob import glob
from dtscalibration import read_sensornet_files

files = glob(r'C:\Users\Bart\Downloads\sensornet\*.ddf')
ds = read_sensornet_files(filepathlist=files)
```
Returns:
```
>>> 20 files were found, each representing a single timestep
>>> Recorded at 2446 points along the cable
>>> The measurement is double ended
>>> 
>>> UserWarning: Sensornet .dff version "Sentinel DTS v5.1" has not been tested.
>>> Please open an issue on github and provide an example file
```

However, it seems like the reversal of the backward measurements is not applied, as the file type is unknown. Can I use the files you supplied to the repository to be able to add tests for this new format?

**Comment by sdattri** [comment]
Yes, please! Let me know when it is tested so that I can use it. Thank you so much!

**Comment by sdattri** [comment]
For your reference: 

[Untitled-1.html.zip](https://github.com/dtscalibration/python-dts-calibration/files/9641535/Untitled-1.html.zip)

**Comment by BSchilperoort** [comment]
The newest version (v1.1.2) on pypi should work. I have updated it to be compatible with the Sentinel files (no warning will show anymore).

You can update in the following way: `pip install dtscalibration --upgrade`

To ensure that the package upgraded successfully, try:
```
>>> import dtscalibration
>>> dtscalibration.__version__
'1.1.2'
```
The version number should be 1.1.2.

**Comment by bdestombe** [comment]
@sdattri Could you reopen the issue if this is not resolved with the fix from @BSchilperoort ?
