### ISSUE TITLE
Deprecate `store_*` kwargs

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#159]
Many of the keyword arguments for the calibration routines relate to what names should be used for certain variables. I am not sure what the use of this is, and it clutters the class with many keyword arguments, which all have to be documented.

We could eliminate 11 / 30 arguments of calibration_double_ended by just imposing the names.

For development sake we can refactor the code by making the variable names constants (defined in, e.g. a separate file). If we really do want to allow users to define their own names, we could add a function `dtscalibration.define_names` that overrides the defaults for the entire module. Users can then call this at the top of their file.

**Comment by bdestombe** [comment]
Very much in favour!

**Comment by bdestombe** [comment]
#178
