### ISSUE TITLE
np.float is depracated

### ISSUE THREAD

**Issue by klapo** [dtscalibration/python-dts-calibration#161]
**Describe the bug**
In `datastore.py`, line 2107, in `calibration_single_ended` the line
`p_cov = np.zeros((p_val.size, p_val.size), dtype=np.float)`
uses the deprecated np.float. It should instead be the new recommended `float` instead (see additional context). It fails when doing a clean install and test (like I am setting up for pyfocs).

**Expected behavior**
It shouldn't throw an error.

**Additional context**
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations.

**Comment by bdestombe** [comment]
Also fixed in #157
