### ISSUE TITLE
Remove restriction for updating to recent xarray

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#167]
**Is your feature request related to a problem? Please describe.**
This package currently requires an xarray from 2022 or before. An issue that would have been resolved by removing this restriction is the following. Xarray currently doesn't work well with pandas 2.0. A recent version of xarray has pandas < 2.0 in it's requirements. Now we have to manually add pandas < 2.0 in our requirements. 

**Describe the solution you'd like**
To support recent versions of xarray. 

**Additional context**
Updating to the most recent stable version of xarray passes all our tests

@BSchilperoort you stated in your commit the following, do you remember what it means? : (temp) fix xarray version, due to groupby overhaul

**Comment by BSchilperoort** [comment]
I am not sure anymore. If everything runs fine now, we should indeed unpin the version. I can do that in #164

**Comment by BSchilperoort** [comment]
The test do break with newer xarray versions. It's due to the following line:

https://github.com/dtscalibration/python-dts-calibration/blob/84c817ed8f5bc5fc656869241f83dfa4cdca8991/src/dtscalibration/datastore.py#L451

This will have to be refactored before we can bump the version.

**Comment by bdestombe** [comment]
I am not sure anymore why we needed that function, as xarray has a resample function of its own. https://github.com/pydata/xarray/blob/main/xarray/core/dataset.py#L9791-L9881
