### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#172]
Could we maybe add it to our tests and allow the test to fail? Just to verify what the issues are that need to be resolved to move forward.

**Comment by bdestombe** [comment]
There are currently no wheels built for netCDF4 on Python 3.11. The issues on their github site shows it is a mess.

https://github.com/Unidata/netcdf4-python/issues/1204

**Comment by BSchilperoort** [comment]
are you sure? I can see the 3.11 wheels on pypi https://pypi.org/project/netCDF4/1.6.4/#files

**Comment by BSchilperoort** [comment]
We should remove the netcdf version pinning: https://github.com/dtscalibration/python-dts-calibration/blob/f0dad9cd2fab9e6e92cd0b8a640402e7c29c4088/pyproject.toml#L65

**Comment by bdestombe** [comment]
I had some troubles with netcdf4 versions later than 1.5.8. So maybe it was me who forgot the comment.

This seems to be related https://github.com/ArtesiaWater/nlmod/issues/161

Shall we pin it to a minimum of 1.6.4?

**Comment by BSchilperoort** [comment]
Yeah, there were some issues. However I think those have been resolved since. Pinning it to >=1.6.4 is probably best.

**Comment by bdestombe** [comment]
Closed with #181
