### ISSUE TITLE
Only first level headers of example notebooks should be included in docs

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#176]
**Describe the bug**
The table of content (https://python-dts-calibration.readthedocs.io/en/latest/) also shows all lower level headers, which looks messy. Excluding those lower level headers should make the toc more readable.

**Comment by BSchilperoort** [comment]
We should probably change to a better theme. For example see https://lilio.readthedocs.io/
When you then open an example notebook (visible in the sidebar) the headers of that notebook will become visible.

![image](https://github.com/dtscalibration/python-dts-calibration/assets/12114825/c37222ad-d1ce-442a-9456-058a5420dc8a)
