### ISSUE TITLE
User-friendly error when setting manually ds.sections

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#200]
**Is your feature request related to a problem? Please describe.**
Raise a user-friendly error when trying to set sections by letting the user know that sections are now set via the calibration functions. Maybe even raise a deprecated error

**Comment by BSchilperoort** [comment]
I guess we can bring back the setter, but just make it throw an error.

```py
@section.setter
def sections(self, value):
    msg = "Not possible anymore!"
    raise DeprecationError(msg)
```

**Comment by BSchilperoort** [comment]
It was just meant to be illustrative ;)
It's also best to split up the error message into multiple lines (with line breaks) so the message stays easily readable.
