### ISSUE TITLE
Release of v3.0.0

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#209]
I recon for patch updates or minor updates we can:
 - start removing code that is not used anymore. Let's identify those parts using by checking the coverage.
 - Importing the accessor directly from the main module

**Comment by BSchilperoort** [comment]
I don't think we need to hurry to get 3.0 out. We can make pre-releases: PyPI supports this as well, and pre-releases won't be installed by pip unless their exact version is specified,

**Comment by bdestombe** [comment]
I worked today on the code to solve the open issues and improve the documentation. #212 Contains in my opinion all that is needed to release v3. What do you think?

**Comment by bdestombe** [comment]
Released v3 so all our efforts of the last 5 months can be installed from pypi

**Comment by BSchilperoort** [comment]
> Released v3 so all our efforts of the last 5 months can be installed from pypi

We could have released a beta version, which could have been installed with `pip install dtscalibration>=3.0.0b`. Let's do this next time if a similar rework comes up, and you want to use the code already before the main release.

Beta releases can also be updated like `3.0.0b2` etc.
