### ISSUE TITLE
Make statsmodels an optional dependency / remove it completely

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#222]
Statsmodels was included only to test the custom sparse solver: 

https://github.com/dtscalibration/python-dts-calibration/blob/b0fcb501dee337ceb32ddebdff60179977dc5d7c/src/dtscalibration/dts_accessor.py#L552-L557

Seeing as it is giving us issues, this is a good moment to make it an optional dependency (or remove it completely), as users don't really need it. It is also not being used in the tests.

Any thoughts @bdestombe ?

**Comment by bdestombe** [comment]
Great catch! Only used it a few times to test and develop solver related
functions.
