### ISSUE TITLE
Include more tests

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#25]
**Is your feature request related to a problem? Please describe.**
Moving forward to include more tests. After correctly configuring codecov we have better insight in which lines of our code is tested and what not. 
https://codecov.io/gh/dtscalibration/python-dts-calibration/tree/master/src/dtscalibration

I would suggest to test the plot functions in example notebooks. Maybe we should introduce a gallery section in the documentation?

**Comment by BSchilperoort** [comment]
Including the plot functions in tests would be a good idea.

In codecov I also saw that there is no test set up for the v4 silixa IO routine... it would be good to include that as well.

**Comment by bdestombe** [comment]
Let's close this issue for now because it is too vaguely posed. 

- Silixa v4 IO is tested
- Plots in the example notebooks are tested. As long as all plotting functions are used in any of the example notebooks, they are tested
- I wouldn't know a better way to test the plotting functions
