### ISSUE TITLE
Error on file read with read_silixa_files

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#26]
**Describe the bug**
When attempting to load the double-ended test files, the following error is returned;

> TypeError:  Cannot convert tz-naive timestamps, use tz_localize to localize

![image](https://user-images.githubusercontent.com/12114825/54365425-1807f680-466f-11e9-85f8-f067ba38123e.png)

**To Reproduce**
1. Install new enviroment
2. Try to use read_silixa_files

**Additional context**
Might be related to the pandas version...
Versions;
- Python: 3.7.1
- Pandas: 0.23.4
- xarray: 0.11.3
- dtscalibration: 0.6.2

**Comment by bdestombe** [comment]
Hi Bart,
Strange.. These errors indeed showed up after a pandas update, but I think I fixed them with a commit on Februari 3.

Are you sure you're using the most resent version? And I think we are testing these io routines, right?

**Comment by BSchilperoort** [comment]
Yes, I am sure I am using version 0.6.2 (the newest one).
I have a fresh install of python, with the listed versions, and got the error.

I assume these routines are tested, as it immediately happens when you try to load the xml files from /tests/data/double_ended/
Which version of pandas do the tests use?

**Comment by bdestombe** [comment]
What is your function call, when you call ``read_silixa_files``?
There should not be the keyword argument `timezone_input_files` in the function call.. Maybe thats it?

**Comment by BSchilperoort** [comment]
I found the issue; the pandas version installed by conda was 0.23.4. With pandas 0.24.2 installed it works.

The change you made is not compatible with older pandas versions, perhaps bump the version requirement to pandas 0.24.2 ?

**Comment by bdestombe** [comment]
Great find! I am using 0.24.1, which also works.
