### ISSUE TITLE
CI tests fail (even for older versions)

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#33]
The Travis & AppVeyor tests currently fail for all commits. When re-running a previously passing test, it now fails.

I am unable to reproduce the bugs locally, and tox tells me nothing is wrong.

**Comment by bdestombe** [comment]
This had to do with e.a. the dependency cloudpickle and locations where numpy arrays were expected, but apparently can now also be Dask arrays. Fixed all of that with #36
