### ISSUE TITLE
Intensity-dependent variance of the noise in (anti-) Stokes measurements

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#34]
In the estimation of the variance of the noise in the measurements, the noise is not assumed to be intensity-dependent. Due to the avalance photodiode, there is an intensity dependent component of the noise in the Stokes & Anti-Stokes measurements. 
This improvement will mainly be necessary for long fiber optic cable setups.
(See dissertation Bas des Tombe, Appendix A)

**Comment by BSchilperoort** [comment]
I had a look at Silixa data. The background noise seems to be minimal (based on the data outside of the measured cable; when the stokes intensity was 0).

The standard deviation seems to have a relatively linear relationship with the Stokes power. Variance does not match up well.

If this hold for other devices, I would recommend estimating the 'beta_+' parameter with a fit through 0, and the least noisy reference section.

![stokes_vs_sigma_ST](https://user-images.githubusercontent.com/12114825/73457953-c777b580-4374-11ea-921c-587f27df2ee3.png)
![stokes_vs_var_ST](https://user-images.githubusercontent.com/12114825/73457955-c777b580-4374-11ea-9fc2-83ec26cdf554.png)

**Comment by bdestombe** [comment]
I wouldn't know why the **standard deviation** of the Stokes noise would scale linear with the Stokes intensity. All the references I've found, treat it as Poisson noise, of which the **variance** of the Stokes noise scales linear with the Stokes intensity.

The noise from the electrical circuit seems indeed to be small compared to the noise from the detectors..

This is what I get for a 2-seconds-acquisition-time measurement with a Silixa Ultima.
![Figure_1](https://user-images.githubusercontent.com/11296133/73533848-09aa0100-4420-11ea-9265-7842db69a230.png)
And with 10 times less bins:
![Figure_2](https://user-images.githubusercontent.com/11296133/73534030-686f7a80-4420-11ea-8c81-1ba7d3a939fd.png)

**Comment by BSchilperoort** [comment]
I think I know how to accurately determine the Stokes intensity dependance.

If you directly take the variance from the internal coil, you overestimate it due to the strong attenuation. You need to detrend the attenuation, and then calculate the variance. This will give a perfect fit.
In the image below I tested this, and also calculated the residuals of the water baths. The two internal coils line up perfectly when fitting a line through (0,0).
![image](https://user-images.githubusercontent.com/12114825/73551190-3e30b380-4446-11ea-8634-8f01225369c6.png)

**Comment by bdestombe** [comment]
Very interesting! Let's discuss on Monday. This seems very promising.

**Comment by bdestombe** [comment]
Linear variance is implemented in v0.8.0. It lacks an example, but its use should be quite straight forward. implemented in `ds.variance_stokes_linear()`

Use:
- `variance_stokes_constant` for small setups with small variations in intensity
- `variance_stokes_exponential` for small setups with very few time steps
- `variance_stokes_linear` for larger setups with more time steps
