### ISSUE TITLE
Add diverging colormap with 0 bias to residual plots

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#35]
Suggestion from Karl. Change the colormap of the residuals to a diverging one, with a 0 value as center.

```
    # Normalize the color scale to have 0 be the center
    divnorm = colors.DivergingNorm(vmin=np.min(bath_lims),
                                   vcenter=0,
                                   vmax=np.max(bath_lims))

...
        # Use the normalized colormap with a zero value at the center.
        im = ax_map.pcolormesh(val.time, val.LAF, val.T,
                               cmap=plt.get_cmap('RdBu'),
                               norm=divnorm)

```

**Comment by bdestombe** [comment]
This is quite a good idea. The primary goal of those plots is to locate patterns in the extreme residuals. The least we could do is to make it optional, but i think this would be indeed a better default. Given vmin and vmax are set to 2% and 98% of the plotted data (robust=True).

**Comment by bdestombe** [comment]
Bart, would you like to take on this Pull Request?

**Comment by BSchilperoort** [comment]
Added with #78
