### ISSUE TITLE
Adding supported filetypes/DTS sensors to the readme

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#47]
To make it clear for people who are linked or stumble upon the package, it could be nice to list all the machines currently supported. e.g.:

**Devices currently supported:**

- Silixa Ltd.
  - Ultima .xml files (up to version 7.0)
  - XT-DTS .xml files (up to version 7.0)
- Sensornet Ltd.
  - Oryx .ddf files
  - Halo .ddf files
- AP Sensing GmbH
  - single ended .xml files
  - .tra files can not supported as they lack the raw signal

**Comment by bdestombe** [comment]
Good idea! Can you add your list to the README.rst ?

**Comment by BSchilperoort** [comment]
Done!
