### ISSUE TITLE
Loading the calibration configuration from the .xml files 

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#50]
Do we want to load the calibration configuration from the xml files? Or should we discourage it, and leave it to the user to come up with a sensible configuration?

**Comment by BSchilperoort** [comment]
I would advise to discourage it, and to have the user set up the configuration manually. This would force the user to think about it more, and secondly, configurations differ a lot per device and manufacturer.

The functions that assist in loading in the data should be about getting the stokes/anti-stokes values into python, and along with it any relevant information (Pt100 data, acquisition time, etc.). The calibration setup should be done by users themselves, to force them to think about what they are doing.

The package is really powerful and allows users to calibrate their data unlike any utility before, but the goal of the package is not to warn users if they have set up their calibration incorrectly, or to warn them if something is going wrong in the calibration setup. The user has to check these things themselves.

**Comment by bdestombe** [comment]
Bart changed my mind with his response, in favour of not including this feature.
