### ISSUE TITLE
Varying length of Silixa .xml files

### ISSUE THREAD

**Issue by rob3rtlaw** [dtscalibration/python-dts-calibration#52]
Sorry for the lengthy title. My problem might provide more context for this.

Due to cable stretch throughout the experiment the overall number of Stokes, aStokes etc. measurements increases with time (only very slightly, e.g. from 4000 to 4001). Whilst this is almost guaranteed in glaciological applications I can see it happening in longer term DTS installations in other environmental projects. 

Unsurprisingly the Dask module throws an error when an increase in array dimensions occurs and I am not sure how to get around it. The optimal solution (feature 1) would be allowance for input of data files of varying length as part of e.g. read_silixa_files . A second solution (feature 2) is to create an empty DataStore of the required dimensions and fill in the data from np.arrays (e.g. ds['time'].values = date_np). In my case I have all the data in np.arrays from my previous processing script before I found out about this library so this would be easy to do. The dtscalibration library functions could then be used on the modified DataStore.

A quick fix to create a DataStore of required dimensions would be to fill a folder full of the correct number of .xml files of maximum length and then amend the values following this, but the other options would be of greater use to other users!

I am happy to put a lot of work into this, but I don't know quite where to begin.

Many thanks,

Rob

**Comment by BSchilperoort** [comment]
Hi Rob,

Thank you for the submission of this issue. I have a few questions which might help clarify the problem.

First a physical one; 
- Are you using a buffered/overstuffed fiber? In general you do not want (varying) strain on your fiber as this affects the differential attenuation. If your differential attenuation is varying over time you would have to split up the calibration in chunks, as the current routines assume constant differential attenuation.

And some data-technical ones:
- How often do the variations in data points occur? Is it oscillating between 4000 and 4001 data points?
- Does a shift of the LAF coordinates take place continuously, or do the LAF coordinates reported by your device only change in steps when the number of data points change?

In the end the only thing that the library requires for calibration is a LAF + ST/aST data set of consistent length. You could already generate this yourself using your previous processing script (and get on with calibrating/analysing the data). However, the correct way to reindex/resample the signal to a consistent size will depend on how the LAF changes.

Could you attach some example files to this issue, so we can have a look at the raw files ourselves?

Regards,
Bart

**Comment by rob3rtlaw** [comment]
Hi Bart,

I am using a ~1% overstuffed cable. The initial processing I was doing was calculation of differential attenuation at every time step, as yes, this varies a significant amount throughout the installation period. 

I had been intending to slightly modify the use of the functions in the dtscalibration library by processing time-averaged (between 4 and 12 hours) sections of the data each with a new series of differential attenuation values. Looking into the files more closely, it appears these changes don't happen frequently, perhaps 5 jumps over the 7,500 files in total. Maybe in this case it is best to simply attend to these jumps manually, unless the fix is fairly easy to implement. Something as simple as a function to pick out the slightly longer measurement files for the users attention might do the trick.

The variations do seem to oscillate, between 11078 an 11079 to be precise. Simply ignoring the handful of files causing the error would not be the end of the world. 

Interestingly, this effect does not seem to be present when the cable becomes damaged to the point of giving unusable readings after 6 weeks in the ice. 

I'm afraid I don't know what 'LAF' is and I can't find it in the documentation, is this later referred to as 'x' within the DataStore?

I have emailed you the files. 

Best wishes,

Rob

**Comment by BSchilperoort** [comment]
Hi Robert,

LAF is length along fiber, which is the (most common) name for what is referenced to as 'x' in this library.  In the Silixa .xml files it is also referenced to as such.

So if I understand it correctly, it's compression by the ice which is causing the strain? This will cause the refractive index of your fiber to change, and therefore the apparent length. 

When using single-ended measurements I don't think you would actually see this happen to the size of the x-dimension. The device does now know what the real refractive index is of your fiber, and uses a constant value to translate the light travel time to LAF. This can be corrected in the device settings as fiber refractive indices vary, but I can see in the .xml files that you did not do this.
What might be happening here is that the device slightly shifts the measurements to align the forward and backward channels. This then causes a change in the size of the x-dimension.

I had a look at the files you send, and the x-coordinates that the device is reporting do not change over time (as the device does not know the fiber's local refractive index). However, I do think they are shifting in reality.

In the end I think it would be best for you to calibrate your data in small chunks, to allow your calibration parameters to vary (as the strain conditions are varying a lot). Here is a small piece of code that will return the size of the x-dimension for each .xml file. You can then determine the chunk boundaries based on the x-dimension size.
```
from glob import glob
import numpy as np
from dtscalibration import read_silixa_files

files = sorted(glob(r'E:\tempdata\varying_x\*.xml'))

ds_files = [read_silixa_files([file], silent=True) for file in files]

dstime = np.array([ds.time.values for ds in ds_files])
dsx = np.array([ds.x.size for ds in ds_files])
```


**Anyway, as for changes to the package;** @bdestombe 
I do not think that the package itself should allow for seamless reading of files of varying length. Varying length will always have some issue deeper down that will mess with the calibration accuracy. However, currently the read_files functions do not cleanly return an error when encountering this.

To fix this issue I think a check will have to be added that ensures that the files are all of the same length. If they are not, a clear error is thrown, which then points the user in the right direction to fixing the problem.



Regards,
Bart

**Comment by BSchilperoort** [comment]
I split up the issue, as creating a DataStore object from scratch is already possible (but never explained/demonstrated). The title is now about the main issue :)

**Comment by rob3rtlaw** [comment]
Hi Bart,

Thanks for the very useful information and tips. I will implement this in my script and should now have everything I need to complete the processing. 

The suggested change sounds very sensible.

Best wishes, 

Rob

**Comment by bdestombe** [comment]
@BSchilperoort The additional check you propose would require additional processing time, because every file needs to be opened to read the parameter nx and to compare the different nx's of all files. Alternatively, we could catch this error when the data is concatenated, but that seems more complicated..

**Comment by BSchilperoort** [comment]
There would be an overhead, yes. However I think that when using ElementTree getting the count of '<data>'  elements should be very quick, and the small overhead would be worth it in user-friendliness.

**Comment by BSchilperoort** [comment]
Looking at the code, I think it would actually be a trivial addition to check, and the right moment is when grab_data_per_file is called. 
In that function, the data is gathered from the elementtree, as a list. The only check that needs to be performed is `nx == len(arr_str)`

**Comment by bdestombe** [comment]
Great! Sounds good to me
