### ISSUE TITLE
Performing WLS calibration on a DataStore that has been averaged across time

### ISSUE THREAD

**Issue by rob3rtlaw** [dtscalibration/python-dts-calibration#58]
I _think_ this would be most accurately described as a bug, but I could be misunderstanding. Basically, whilst ds.calibration_double_ended and ds.conf_int_double_ended function correctly when the DataStore is comprised of only one DTS file, an error is thrown if using a DataStore that has previously been average through ds.mean(dim='time', keep_attrs=True). 

As far as I can tell, this is because the DataStore looses its time dimension, though it does still represent _a_ time even if just an average one. I have a work around where I take everything out of the averaged DataStore and create a new one with a time dimension which does work, but built in capability might help others avoid this problem. 

Kind regards,

Rob

**Comment by bdestombe** [comment]
Hi Rob,
Thanks for reporting. The problem that you encounter sounds very familiar. But it is quite difficult to solve as this is seen as a feature in xarray (a Python package of which much is inherited). I might have some time next week to look at it.

Meanwhile, there are several things you could try.
- Does ds.mean(dim='time', keep_attrs=True, keepdims=True) work? (https://github.com/pydata/xarray/commit/ff4198865b42ee2f6f99f3f6f83fed68ef4ffbc7)
- Maybe you could stack a copy of your averaged object to your averaged object and then perform your calibration? You would have twice the same information, which would give the same outcome. Maybe not the most elegant solution though

But aren't you maybe looking for `ci_avg_time_flag` in ds.conf_int_double_ended(..)  ?https://github.com/dtscalibration/python-dts-calibration/blob/9d4e58d1821ddad863224a31a089c912b773edd5/src/dtscalibration/datastore.py#L2159

**Comment by rob3rtlaw** [comment]
Hi Bas,

Thanks for the tips. Your first suggestion does work! The ci_avg_time_flag should also work.

Many thanks,

Rob

**Comment by bdestombe** [comment]
Perfect!
