### ISSUE TITLE
Subaxes in residuals plot function do not share axes

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#59]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11296133/69954836-9148c180-14fc-11ea-83f8-4f99eae322f9.png)
The left axes do not share the same x-axis. Furthermore, my preference would be to flip the x-axis, so that it increases to the left.

**To Reproduce**
With the following function: ```from dtscalibration.plot import plot_residuals_reference_sections```

**Comment by BSchilperoort** [comment]
I've noticed this issue before. The axes do share the same x-axis (which is clear if you drag the plots in interactive mode). I quickly made a small change where the limits are set for all x-avg plots, fixing this matplotlib update/display issue.

My personal preference would not be to flip the x-axis, what would be a logical reason to flip the axis? This is not be clear to me.

**Comment by bdestombe** [comment]
That is fast.. Great!

nvm. It is a personal preference, maybe because I was used to looking at a plot with that axis reversed.
