### ISSUE TITLE
Cable shift suggestion uncertain with 'smooth' Stokes data

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#62]
If the Stokes signal is too smooth, the cable shift suggestion does not seem to work properly. 
~~Perhaps using the Anti-Stokes data would help with accurately suggesting a cable shift.~~

An image to illustrate the problem is shown below.

![image](https://user-images.githubusercontent.com/12114825/70336155-ef510e00-1848-11ea-89a1-5ee331ed737b.png)

**Comment by bdestombe** [comment]
The current implementation requires indeed spatial variation in signal intensity. It minimizes the length of the differences.

PRs are welcome that do not require spatial variation in the signal intensity. For now, I am closing the issue.
