### ISSUE TITLE
Fix gamma not working for double ended calibration

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#64]
When attempting to fix only the gamma parameter, an error is returned. When fixing no parameters, the calibration runs as expected.

The error claims there is a size conflict between 'alpha' and 'ST', but no fixed diff. attenuation was provided. 

![image](https://user-images.githubusercontent.com/12114825/70443805-1736b080-1a99-11ea-9742-dad2fed87457.png)

**Comment by bdestombe** [comment]
Hi Bart,
I believe this is fixed now. Feel free to reopen this issue if it isn't.
