### ISSUE TITLE
Sensornet data inconsistent backward channel direction

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#75]
For double ended Sensornet .ddf datafiles (Halo DTS v1.0), our test data has the backward channel reversed (strong signal near 0), and thus we flip the backward channel data.

For other devices (at least Oryx v4), the backward channel is already properly aligned, and is now needlessly flipped. 

For proper support we will have to check the file versions, and use that to either flip the backward channel or not.

**Comment by johannespopma** [comment]
In the zip file some data files are given in which the described issue in issue 94 occurs.
In the files the software version number of the oryx system is described as: 
ORYX F/W v4,00 Oryx Data Collector v3.7.3

[OryxDataCollectorv3.7.3.zip](https://github.com/dtscalibration/python-dts-calibration/files/4328269/OryxDataCollectorv3.7.3.zip)

**Comment by bdestombe** [comment]
Thanks, I will make the changes.

**Comment by BSchilperoort** [comment]
Changing it should be straightforward. The data is reversed on [this line](https://github.com/dtscalibration/python-dts-calibration/blob/54b35fdc87f9c1799aea9137f49f79b79a33fcf0/src/dtscalibration/io.py#L841).

A version check of the sensornet files will be necessary. The version info is in the _meta_ dictionary, read in [here](https://github.com/dtscalibration/python-dts-calibration/blob/54b35fdc87f9c1799aea9137f49f79b79a33fcf0/src/dtscalibration/io.py#L727). 
For the "Halo DTS v1.0" files double ended data has to be reversed (as it is now).

**Comment by bdestombe** [comment]
#95

**Comment by bdestombe** [comment]
Should be fixed now with #95
