### ISSUE TITLE
Drop 32-bit Windows tests

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#83]
**Describe the bug**
Currently, the automated 32-bit tests on the Windows platform, ran by Appveyor, are failing, #80 . It is quite annoying to debug because I don't have any 32-bit computer laying around. 

I am not sure of any computer currently being sold that is 32-bit, except for the raspberry pi. Furthermore, since we are using a coding language that is quite far away from all the bits and bytes, 32-bit / 64-bit should be not of our concern.

What do you think?

**To Reproduce**
What I think is going on:
1. Run 32-bit Python on windows 64-bit, on a 64-bit machine.
2. Your linear algebra libraries are then running natively in 64 bit
3. Python works in 32-bit
4. Scipy get confused

**Expected behavior**
See 64-bit Python behavior

**Additional context**
Seems to be related to https://github.com/scipy/scipy/issues/4524

**Comment by BSchilperoort** [comment]
I'm installing a 32-bit python on windows now to see if I can reproduce the issue.

**Comment by BSchilperoort** [comment]
I think this is a floating point precision issue again. This is from running the test *test_double_ended_ols_wls_fix_alpha_estimate_synthetic* on windows with 32 bit python:
![image](https://user-images.githubusercontent.com/12114825/74831349-61e46c80-5315-11ea-96b2-a9791991bd4a.png)


I think easing up the tests to be less precise will allow these tests to pass, without a chance of introducing any false negatives. 6 or 7 decimals should be more than sufficient for parameters such as TMPF and gamma. The precision will need to be scaled to the value of the parameters you are comparing (as a floating point number's precision depends on its value)


For example a gamma value of 480.000000 vs 479.999999 will not be from errors in the matrices, but will just be down to floating point errors. The more operations you do on the original value, the more precision you will lose.


When displaying the values in python, it truncates them to look the same, but there is still a difference:
![image](https://user-images.githubusercontent.com/12114825/74831843-56de0c00-5316-11ea-898a-c679b9fd6c0d.png)


You can also see the difference when looking at the hexadecimal string
![image](https://user-images.githubusercontent.com/12114825/74832090-cf44cd00-5316-11ea-93b9-b351f001e608.png)

At first the synthetic tests failed on this 64 bit windows installation with 32 bit python. I adjusted the precision of the synthetic tests (6 decimals, 8 decimals for alpha), and now all tests pass.

**Comment by BSchilperoort** [comment]
I might have performed the wrong test before (did not get the pull request version, just the latest master).
I have now tried the PR version, which fails on appveyor, but on my machine there are no issues.

I have used the following setup
- Windows 10 64-bits
- Python 3.6 32-bit
- Python 3.7 32 bit

**Comment by bdestombe** [comment]
Great work! Too bad it remains a pain.

Oh sorry, that was my bad.. I've put all those decimal precision assertion commits in the same pull request as the double-ended calibration overhaul.

I see several possibilities:
 - actually solving the problem on Appveyor. This would require many commits and is time consuming.
 - Try instead of giving zero variance to the fixed alpha, a small variance and see if computing the SVD is less problematic. 
 - A hacky solution like in this particular test: if platform is win32: pass; else continue with the test.
 - Make win32 on Appveyor an optional test which may fail.
 - Remove win32 tests from Appveyor

**Comment by BSchilperoort** [comment]
I would not know what is actually going wrong on Appveyor, as it works fine on windows on my laptop. My choice at the moment would be to make the win32 tests of Appveyor optional for now, and see if the problem goes away by itself. If it remains an issue for a while, we can have a look at it later.

**Comment by bdestombe** [comment]
For now, the 32 bit tests are set to not critical, and is allowed to fail. Please create a new issue if tests fail on your 32 bit system.
