### ISSUE TITLE
vmin, vmax in plot_residuals_reference_sections

### ISSUE THREAD

**Issue by dbrakenhoff** [dtscalibration/python-dts-calibration#84]
**Describe the bug**
In `plot_residuals_reference_sections` there is a bit of code that sets `vmin` to `-vmax` if `vmin` is less than 0:
https://github.com/dtscalibration/python-dts-calibration/blob/c85d615ef19fb75c14b55aa3a7f0741c25fabf56/src/dtscalibration/plot.py#L170-L172

This causes an error when both `vmin` and `vmax` are negative (I'm sure that also means the result isn't too good, but anyway). In that situation, `vmin` becomes positive and `vmax` is negative causing an error in `colors.DivergingNorm`. It probably also fails if both are positive...

And another thing, wouldn't it make more sense to use the largest of the two to set up your colormap? Now `vmax` determines what the maximum value should be. Maybe something along these lines would be nicer:
```python
maxv = np.max(np.abs([vmin, vmax]))
vmin = -maxv
vmax = maxv
```

**To Reproduce**
Plot using `plot_residuals_reference_sections` with residuals in which the quantiles 0.02 and 0.98 are both negative.

**Expected behavior**
Don't crash when someone tries that?

**Comment by BSchilperoort** [comment]
Hi Davíd, thank you for reporting this issue! It indeed did not work as it should.
I have [fixed this issue](https://github.com/dtscalibration/python-dts-calibration/commit/f858f958bfa18bb8d09f29d89d3db7ef869970a3), and used your suggestion which looked like the perfect way to do it.
