### ISSUE TITLE
Cannot calculate conf. ints. in a double-ended calibration with trans.att.

### ISSUE THREAD

**Issue by BSchilperoort** [dtscalibration/python-dts-calibration#91]
After successfully calibrating a double-ended dataset with a transient attenuation location added, there is an assertion error when trying to calculate the confidence intervals.

Apparently p_val is not of the expected size
![image](https://user-images.githubusercontent.com/12114825/75868322-2b741a80-5e08-11ea-99af-756069ff45e1.png)

Calculating the confidence intervals works fine when not adding the trans. att.

**Comment by bdestombe** [comment]
You're completely right! Completely forgot to test the confidence intervals..

**Comment by rob3rtlaw** [comment]
Hi both, I wondered if this had been implemented? I just tried again using version 0.8.0 and came up with the same AssertionError 'in conf_int_double_ended assert p_val.shape == (npar,)'. I can switch back to non-matching sections if required.

Cheers,
Rob

**Comment by bdestombe** [comment]
Hi Rob,
I am working on it. A fix is part #93 . Let's see if it passes the tests and whether we can merge it into the package tomorrow. 

Cheers,
Bas

**Comment by rob3rtlaw** [comment]
Hi Bas, amazing, thanks a lot.

**Comment by bdestombe** [comment]
Hi Rob,
It is merged so I'm closing the issue. If you have any difficulties feel free to reopen this issue.

Bas
