### ISSUE TITLE
Temperature reduction by applying a user-defined function over a timeseries

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#92]
**Describe the solution you'd like**
Something like:
```python
def ufunc(time, temp, *args, **kwargs):
    # super complicated function
    ...
    return velocity

ds['velocity'] = ds.apply_user_func(func, time_label='time', temp_label='TMPW', ufunc_args=None, ufunc_kwargs=None)
```
where `ds['velocity'] ` is a DataArray with dimension `x` (no `time` dimension). ufuncs_args and ufuncs_kwargs are directly passed to ufuncs. Normally one would do this by iteration using a for loop, and apply the ufunc to each point along the cable. Instead we could implement something like that, but in parallel, using chunks with Dask.

My question is, is this of interrest? And what additional features would you need yourself?

**Comment by BSchilperoort** [comment]
When I am doing my analysis of the data, I'm generally not using dtscalibration anymore. The full datastore objects are too big and numerous, and my data is transformed into a different coordinate system. So for me personally this does not have too much use.

**Comment by bdestombe** [comment]
Sounds fair, so it's beyond the scope of this package. I'll close it then :) Thanks for you opinion.

I would still like one day to have like these notebooks with different applications
