### ISSUE TITLE
Double-ended measurements made by an Oryx are not reversed

### ISSUE THREAD

**Issue by bdestombe** [dtscalibration/python-dts-calibration#94]
**Describe the bug**
The reversed Stokes and anti Stokes are not aligned with the Stokes and anti-Stokes of the forward direction.

![image](https://user-images.githubusercontent.com/11296133/76534877-5ac6ff00-647a-11ea-8d62-2b3c9c3d2583.png)
A figure of Johannes showing the Stokes of a forward and of a backward measurement.

**Expected behavior**
It is expected that the reverse Stokes are strongest at the far end of the fiber.

**Comment by BSchilperoort** [comment]
I was made aware of the bug and did open an issue. Depending on the software version of the sensornet device it either flips it or not. It's an easy fix, but I do not have the data files to test and fix this. If someone could provide a file with this issue I can fix it.

**Comment by BSchilperoort** [comment]
Copy of #75

**Comment by bdestombe** [comment]
Sorry Bart, I missed that you already formulated the issue
